# Generated by Django 3.2.12 on 2022-04-01 17:15

from django.db import migrations, models
import myDrowsinessDetectionApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('mobile_number', models.IntegerField()),
                ('four_digit_pin', models.IntegerField()),
                ('confirm_four_digit_pin', models.IntegerField()),
                ('daily_driving_hours', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[(myDrowsinessDetectionApp.models.gender_type['M'], 'Male'), (myDrowsinessDetectionApp.models.gender_type['F'], 'Female')], max_length=5)),
                ('vehicle_type', models.CharField(choices=[(myDrowsinessDetectionApp.models.vehicle_list_type['Car'], 'Car'), (myDrowsinessDetectionApp.models.vehicle_list_type['Bus'], 'Bus'), (myDrowsinessDetectionApp.models.vehicle_list_type['Truck'], 'Truck')], max_length=5)),
            ],
            options={
                'db_table': 'driver_details',
            },
        ),
    ]
